package api

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"sidey/internal/audit"
	"sidey/internal/jobs"
)

// exportP12Timeout bounds how long a certificate download waits for the
// signing worker to produce the archive (worker poll + Apple login + CSR).
const exportP12Timeout = 2 * time.Minute

type exportP12Result struct {
	P12Base64   string `json:"p12_base64"`
	P12Sha256   string `json:"p12_sha256"`
	CertSerial  string `json:"cert_serial"`
	TeamID      string `json:"team_id"`
	MachineName string `json:"machine_name"`
	MachineID   string `json:"machine_id"`
}

// handleAppleCertificateDownload enqueues (or reuses) a certificate p12
// export job for the account and streams the PKCS#12 archive back once the
// signing worker has produced it. Completed exports are cached in the job
// result keyed by idempotency_key, so subsequent downloads for the same
// account are served immediately without re-running the export.
func (s *Server) handleAppleCertificateDownload(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": "invalid account id"})
		return
	}
	var label string
	err = s.pool.QueryRow(r.Context(),
		`SELECT label FROM apple_accounts WHERE id = $1`, id).Scan(&label)
	if errors.Is(err, pgx.ErrNoRows) {
		writeJSON(w, http.StatusNotFound, map[string]any{"error": "apple account not found"})
		return
	}
	if err != nil {
		s.writeError(w, http.StatusInternalServerError, "loading account failed")
		return
	}

	waitCtx, cancel := context.WithTimeout(r.Context(), exportP12Timeout)
	defer cancel()

	p12, serial, machineID, err := s.awaitExportP12(waitCtx, label)
	if err != nil {
		if errors.Is(err, context.DeadlineExceeded) {
			writeJSON(w, http.StatusAccepted, map[string]any{
				"status":  "pending",
				"message": "Certificate export is being generated by the signing worker; retry the download in a few seconds.",
			})
			return
		}
		writeJSON(w, http.StatusBadGateway, map[string]any{"error": err.Error()})
		return
	}

	if machineID != "" {
		w.Header().Set("X-P12-Password", machineID)
	}
	s.audit.Record(r.Context(), "admin", "certificate.exported",
		audit.WithData(map[string]any{"account_id": id, "cert_serial": serial}))

	w.Header().Set("Content-Type", "application/x-pkcs12")
	w.Header().Set("Content-Disposition",
		fmt.Sprintf("attachment; filename=%q", fmt.Sprintf("ALTCertificate-%s.p12", serial)))
	w.Header().Set("Access-Control-Allow-Origin", "*")
	_, _ = w.Write(p12)
}

// awaitExportP12 ensures a single export_p12 job exists for the account
// (idempotent via idempotency_key) and polls it to completion, returning the
// decoded PKCS#12 archive, certificate serial, and the p12 password (the
// certificate's machine_id). A failed/dead job is purged and recreated once so
// a transient failure can be retried by the caller.
func (s *Server) awaitExportP12(ctx context.Context, appleID string) ([]byte, string, string, error) {
	key := "export_p12:" + appleID
	params := json.RawMessage(
		fmt.Sprintf(`{"apple_id":%q,"machine_name":"isideload-minimal"}`, appleID))

	create := func() (*exportJobSnapshot, error) {
		job, err := s.jobs.Create(ctx, "admin", jobs.CreateRequest{
			JobType:        jobs.JobTypeExportP12,
			Parameters:     params,
			IdempotencyKey: key,
		})
		if err != nil {
			return nil, fmt.Errorf("enqueuing certificate export failed: %w", err)
		}
		return &exportJobSnapshot{
			ID: job.ID, State: job.State, Result: job.Result,
			ErrCat: derefString(job.ErrorCategory), ErrDet: derefString(job.ErrorDetails),
		}, nil
	}

	snap, err := create()
	if err != nil {
		return nil, "", "", err
	}
	retried := false
	for {
		if snap.State == jobs.StateCompleted && len(snap.Result) > 0 {
			var res exportP12Result
			if err := json.Unmarshal(snap.Result, &res); err == nil && res.P12Base64 != "" {
				p12, derr := base64.StdEncoding.DecodeString(res.P12Base64)
				if derr == nil {
					return p12, res.CertSerial, res.MachineID, nil
				}
			}
		}
		switch snap.State {
		case jobs.StateFailed, jobs.StateDead:
			if retried {
				detail := snap.ErrDet
				if detail == "" {
					detail = snap.ErrCat
				}
				return nil, "", "", fmt.Errorf("certificate export failed: %s", detail)
			}
			// Purge the poisoned idempotency key and recreate once.
			_, _ = s.pool.Exec(ctx, `DELETE FROM jobs WHERE idempotency_key = $1`, key)
			retried = true
			snap, err = create()
			if err != nil {
				return nil, "", "", err
			}
			continue
		case jobs.StatePending, jobs.StateClaimed, jobs.StateInProgress:
			// still cooking
		default:
			select {
			case <-ctx.Done():
				return nil, "", "", ctx.Err()
			default:
			}
		}
		select {
		case <-ctx.Done():
			return nil, "", "", ctx.Err()
		case <-time.After(2 * time.Second):
		}
		snap, err = s.exportJobSnapshot(ctx, snap.ID)
		if err != nil {
			return nil, "", "", err
		}
	}
}

type exportJobSnapshot struct {
	ID     uuid.UUID
	State  string
	Result json.RawMessage
	ErrCat string
	ErrDet string
}

func (s *Server) exportJobSnapshot(ctx context.Context, id uuid.UUID) (*exportJobSnapshot, error) {
	var snap exportJobSnapshot
	var errCat, errDet *string
	err := s.pool.QueryRow(ctx, `
		SELECT id, state, result, error_category, error_details
		FROM jobs WHERE id = $1`, id).
		Scan(&snap.ID, &snap.State, &snap.Result, &errCat, &errDet)
	if err != nil {
		return nil, fmt.Errorf("loading export job failed: %w", err)
	}
	if errCat != nil {
		snap.ErrCat = *errCat
	}
	if errDet != nil {
		snap.ErrDet = *errDet
	}
	return &snap, nil
}

func derefString(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}
